ENCODER_MAP_ENABLE = yes

OLED_ENABLE= yes
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c
CONVERT_TO = rp2040_ce
MOUSEKEY_ENABLE = yes
# KEY_OVERRIDE_ENABLE = yes
OS_DETECTION_ENABLE = yes

# Enable per-key lighting
RGB_MATRIX_ENABLE = no
